version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - ./gradlew -Dflyway.configFiles=/src/main/resources/database-production.conf flywayMigrate
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew bootJar
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd
artifacts:
  files:
    - build/libs/*.jar
cache:
  paths:
    - '/root/.gradle/caches/**/*'
